### ISSUE TITLE
Error when using blob.write and passing in a string

### ISSUE THREAD

**Issue by svaj** [tracker1/node-azure-storage-simple#1]
https://github.com/tracker1/node-azure-storage-simple/blob/3205ada2289b066d45da60da68c5b2b4ba125eec/src/blob/write-buffer.js#L21
That line should probably be returning saveText() as safeText() is undefined.

**Comment by tracker1** [comment]
@svag do you need this in node < 8.5?

Adding the patch in, but removing the entire build system and updating some dependencies... they aren't necessary in node >= 8.5 (async enabled by default).  Will publish a new major version shortly.

**Comment by tracker1** [comment]
@svaj looks like it *should* work okay in node 4+ ... but I'm unable to test... I've published a new major version, if you want to give it a try.
